services:
  postgres:
    image: postgres:15
    container_name: mama_postgres
    environment:
      POSTGRES_DB: mama_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sethan8r
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mama_app
    ports:
      - "8080:8080"
    volumes:
      - C:/logs:/app/logs
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mama_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sethan8r

volumes:
  postgres_data: