server:
  port: 8080

spring:
  application:
    name: mama

  datasource:
#    url: jdbc:postgresql://postgres:5432/mama_db
    url: jdbc:postgresql://localhost:5433/mama_db
    username: postgres
    password: sethan8r

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB      # Максимальный размер одного файла
      max-request-size: 10MB   # Максимальный размер всего запроса